// GENERATED by tatara-rust-derive::PerVariantDeriveSpec.
use proc_macro::TokenStream;
use quote::quote;
use syn::{Data, DataEnum, DeriveInput, Fields, parse_macro_input};

#[proc_macro_derive(IsVariant)]
pub fn derive_is_variant(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    let self_name = &input.ident;

    let variants = match &input.data {
        Data::Enum(DataEnum { variants, .. }) => variants,
        _ => {
            return syn::Error::new_spanned(self_name, "PerVariantDerive requires an enum").to_compile_error().into();
        }
    };

    let per_variant = variants.iter().map(|v| {
        let variant_name = &v.ident;
        let variant_shape_arm = match &v.fields {
            Fields::Named(_)   => quote! { Self::#variant_name { .. } },
            Fields::Unnamed(_) => quote! { Self::#variant_name(..) },
            Fields::Unit       => quote! { Self::#variant_name },
        };
        let method_ident = quote::format_ident!("is_{}", variant_name.to_string().to_lowercase());
        quote! {
            pub fn #method_ident(&self) -> bool { matches!(self, #variant_shape_arm) }
        }
    });

    let expanded = quote! {
        impl #self_name {
            #(#per_variant)*
        }
    };
    TokenStream::from(expanded)
}
